function qsTr(a) {
    return a;
}

langBase = {};
langBase.en = {
    confirm: qsTr("confirm please"),
    websocketError: qsTr("Websocket error check network please"),
    alertWaiting: qsTr("undeveloped "),
    changeChannel: qsTr("setChn"),
    websitegate: qsTr("GATE"),
    promptssid: qsTr("set SSID please"),
    promptpassword: qsTr("set Password"),
    lang: qsTr("ENGLISH"),
    FX_ECHO: qsTr("echo"),
    FX_DELAY: qsTr("Delay"),
    HOME: qsTr("HOME"),
    FX_REVERB: qsTr("Reverb"),
    ChannelSet: qsTr("Chn-Set"),
    SceneShot: qsTr("Scene"),
    VUDis: qsTr("VUDis"),
    FXSend: qsTr("FX-Send"),
    MainSend: qsTr("M-Send"),
    BASESET: qsTr("BASESET"),
    MAINALLO: qsTr("MAINALLO"),
    USBREC: qsTr("REC"),
    LINK: qsTr("LINK"),
    COLOR: qsTr("COLOR"),
    APPLY: qsTr("APPLY"),
    COVER: qsTr("COVER"),
    MAIN_OUT: qsTr("MASTER OUT"),
    me_REVERB: qsTr("REVERB"),
    GLOBALSET: qsTr("GLOBALSET"),
    ASSIGN_SUB_GROUP: qsTr("ASSIGN SUB GROUP {0}"),
    ATTACK: qsTr("ATTACK"),
    SCENEHANDLE: qsTr("WHAT DO YOU WANT FOR ({0}) ?"),
    SCENENAME: qsTr("NAME"),
    AUX: qsTr("AUX"),
    AUX_EQ: qsTr("AUX EQ"),
    AUX_MASTERS: qsTr("AUX MASTERS"),
    AUX_MASTER_LEVELS: qsTr("AUX MASTER LEVELS"),
    AUX_SENDS_FOR: qsTr("AUX SENDS: {0}"),
    BANKS: qsTr("BANKS"),
    BASS_GAIN: qsTr("BASS GAIN"),
    BYPASS: qsTr("BYPASS"),
    CH: qsTr("CH"),
    CHANNEL_SAFES: qsTr("CHANNEL SAFES"),
    FX_SENDS_X: qsTr("FX SENDS: {0}"),
    CHANNEL_PRESETS: qsTr("CHANNEL PRESETS"),
    CHORUS: qsTr("CHORUS"),
    CHORUS_FX_GLOBAL: qsTr("CHORUS FX (GLOBAL)"),
    CLEAR_SOLO: qsTr("CLEAR SOLO"),
    CONFIG: qsTr("CONFIG"),
    CONFIGURATION: qsTr("CONFIGURATION"),
    CONNECTED_DEVICE_NAME: qsTr("CONNECTED DEVICE NAME"),
    COPY_SETTINGS: qsTr("COPY SETTINGS"),
    CURRENT_SHOW: qsTr("CURRENT SHOW"),
    DELAY: qsTr("DELAY"),
    DELAY_FX_GLOBAL: qsTr("DELAY FX (GLOBAL)"),
    DELAY_LENGTH: qsTr("DELAY LENGTH"),
    DELETE: qsTr("DELETE"),
    DISABLE_STEREO_LINK: qsTr("DISABLE STEREO LINK"),
    DOCUMENTATION: qsTr("DOCUMENTATION"),
    DYN: qsTr("DYN"),
    EDIT: qsTr("EDIT"),
    EQ: qsTr("EQ"),
    EXPORT: qsTr("EXPORT"),
    FAV_SHOW: qsTr("FAVOURITE SHOW"),
    FEEDBACK: qsTr("FEEDBACK"),
    FEEDBACK_AMOUNT: qsTr("FEEDBACK AMOUNT"),
    FREQ: qsTr("FREQ"),
    FX: qsTr("FX"),
    FX_MODE_DEFAULT: qsTr("FX MODE DEFAULT"),
    FX_RETURNS: qsTr("FX RETURNS"),
    FX_RETURNS_TO_AUX: qsTr("FX RETURNS TO {0}"),
    GAIN: qsTr("GAIN"),
    PREGAIN: qsTr("PreGain"),
    GROUP: qsTr("GROUP"),
    HELP: qsTr("HELP"),
    HF_DAMPING: qsTr("HF DAMPING"),
    HIGHPASS_FILTER: qsTr("HIGHPASS FILTER"),
    IMPORT: qsTr("IMPORT"),
    INPUT: qsTr("INPUT"),
    LED: qsTr("LED"),
    LENGTH_SUBDIVISION: qsTr("LENGTH SUBDIVISION"),
    LOAD: qsTr("LOAD"),
    LOAD_PRESET: qsTr("LOAD PRESET"),
    LOCK: qsTr("LOCK"),
    LOCKED: qsTr("LOCKED"),
    LOWPASS_FILTER: qsTr("LOWPASS FILTER"),
    MANUAL: qsTr("MANUAL"),
    MASTER: qsTr("MASTER"),
    MASTER_EQ: qsTr("MASTER EQ"),
    MEDIA: qsTr("MEDIA"),
    MEDIA_FADER_BEFORE_CH1: qsTr("MEDIA FADER BEFORE CH1"),
    MIX_GAIN: qsTr("MIX GAIN"),
    MUTE: qsTr("MUTE"),
    MUTE_ALL: qsTr("MUTE ALL"),
    MUTE_FX: qsTr("MUTE FX"),
    MUTE_GROUP_BUTTON_ASSIGN: qsTr("MUTE GROUP BUTTON ASSIGN"),
    MUTE_GROUPS: qsTr("MUTE GROUPS"),
    MUTES: qsTr("MUTES"),
    NETWORK: qsTr("NETWORK"),
    NEW: qsTr("NEW"),
    NEW_SNAPSHOT: qsTr("NEW SNAPSHOT"),
    NEXT_SNAPSHOT: qsTr("NEXT SNAPSHOT"),
    NORM: qsTr("NORM"),
    OFF: qsTr("OFF"),
    ON: qsTr("ON"),
    ONLINE_SUPPORT: qsTr("ONLINE SUPPORT"),
    PASTE_SETTINGS: qsTr("PASTE SETTINGS"),
    PERMISSIONS: qsTr("PERMISSIONS"),
    PERMIT: qsTr("PERMIT"),
    PHANTOM: qsTr("PHANTOM"),
    PLAY: qsTr("PLAY"),
    PLAYER: qsTr("PLAYER"),
    PLAYLIST: qsTr("PLAYLIST"),
    PRESETS: qsTr("PRESETS"),
    RATIO: qsTr("RATIO"),
    RECORD: qsTr("RECORD"),
    RELEASE: qsTr("RELEASE"),
    RENAME: qsTr("RENAME"),
    RESET: qsTr("RESET"),
    RESET_CHANNEL: qsTr("RESET CHANNEL"),
    REVERB: qsTr("REVERB"),
    REVERB_TIME: qsTr("REVERB TIME"),
    REVERB_FX_GLOBAL: qsTr("REVERB FX (GLOBAL)"),
    ROOM: qsTr("ROOM"),
    SAVE: qsTr("SAVE"),
    SAVE_AS: qsTr("SAVE AS"),
    SEND: qsTr("SEND"),
    SENDS: qsTr("SENDS"),
    SG: qsTr("SG"),
    SHOWS: qsTr("SHOWS"),
    SNAPSHOTS: qsTr("SNAPSHOTS"),
    SOCIAL: qsTr("SOCIAL"),
    SOLO: qsTr("SOLO"),
    SPEED: qsTr("SPEED"),
    STEREO_LINK: qsTr("STEREO LINK"),
    SUB_GROUP_FADER_ASSIGN: qsTr("SUB GROUP FADER ASSIGN"),
    SUB_GROUP_SPREAD: qsTr("SUB GROUP SPREAD"),
    SUB_GROUPS: qsTr("SUB GROUPS"),
    SUBS: qsTr("SUBS"),
    SUB: qsTr('SUB'),
    TAP_TEMPO: qsTr("TAP TEMPO"),
    THIN: qsTr("THIN"),
    TOTAL_VIEW: qsTr("TOTAL VIEW"),
    UNASSIGN_SUB_GROUP: qsTr("UNASSIGN SUB GROUP {0}"),
    UPDATE_CURRENT_SNAPSHOT: qsTr("UPDATE CURRENT SNAPSHOT"),
    USB_MEDIA_FILES: qsTr("USB MEDIA FILES"),
    VIEW_GROUP_BUTTON_ASSIGN: qsTr("VIEW GROUP BUTTON ASSIGN"),
    VIEW_GROUPS: qsTr("VIEW GROUPS"),
    VIEWS: qsTr("VIEWS"),
    SHOW_ALL_CHANNELS: qsTr("SHOW ALL CHANNELS"),
    PLACE_AFTER_INPUTS: qsTr("PLACE AFTER INPUTS"),
    PLACE_BEFORE_INPUTS: qsTr("PLACE BEFORE INPUTS"),
    GATE: qsTr("GATE"),
    MUTE_FX_CANCEL: qsTr("MUTE FX CANCEL"),
    MUTE_ALL_CANCEL: qsTr("MUTE ALL CANCEL"),
    MUTEGROUP_1_ACTIVATED: qsTr("MUTE GROUP {0} ON"),
    MUTEGROUP_1_DEACTIVATED: qsTr("MUTE GROUP {0} OFF"),
    NO_SNAPSHOT: qsTr("NO SNAPSHOT"),
    LOAD_NEXT_SNAPSHOT: qsTr("LOAD NEXT SNAPSHOT"),
    CHANNEL_EQ_PRESETS: qsTr("CHANNEL EQ PRESETS"),
    AUX_EQ_PRESETS: qsTr("AUX EQ PRESETS"),
    MASTER_EQ_PRESETS: qsTr("MASTER EQ PRESETS"),
    CHANNEL_DYN_PRESETS: qsTr("CHANNEL DYN PRESETS"),
    AUX_DYN_PRESETS: qsTr("AUX DYN PRESETS"),
    MASTER_DYN_PRESETS: qsTr("MASTER DYN PRESETS"),
    DELAY_FX_PRESETS: qsTr("DELAY FX PRESETS"),
    CHORUS_FX_PRESETS: qsTr("CHORUS FX PRESETS"),
    REVERB_FX_PRESETS: qsTr("REVERB FX PRESETS"),
    ROOM_PRESETS: qsTr("ROOM PRESETS"),
    DIGITECH_PRESETS: qsTr("DIGITECH PRESETS"),
    UX_PRESETS: qsTr("OPTIONS PRESETS (LOCAL)"),
    FILES: qsTr("FILES"),
    CONNECTING: qsTr("Connecting..."),
    KEEP_TAPPING: qsTr("KEEP TAPPING..."),
    PLAYLISTS: qsTr("PLAYLISTS"),
    PRESET_LOADED: qsTr("PRESET<br>{0}<br>LOADED"),
    NO_PAN_ON_MONO_AUX: qsTr("NO PAN<br>ON MONO AUX"),
    PARAM_GLOBAL: qsTr("{0} PARAMETERS (GLOBAL)"),
    CLEAR_ALL_SOLOS: qsTr("CLEAR ALL SOLOS"),
    POST: qsTr("POST"),
    PRE: qsTr("PRE"),
    SET_ALL_CHANNELS_TO: qsTr('SET ALL CHANNELS TO "{0}" ?'),
    SAVED: qsTr("SAVED"),
    REPLACE_PRESET: qsTr('REPLACE PRESET "{0}"?'),
    REPLACE_SNAPSHOT: qsTr('REPLACE SNAPSHOT "{0}"?'),
    FACTORY: qsTr("FACTORY"),
    USER: qsTr("USER"),
    DELETE_PRESET: qsTr('DELETE PRESET "{0}" ?'),
    BPM: qsTr("BPM"),
    OUT_OF_RANGE: qsTr("OUT OF RANGE"),
    ERROR: qsTr("ERROR"),
    ENTER_BPM: qsTr("ENTER BPM"),
    NO_ASSIGNED_SUBGROUP: qsTr("NO ASSIGNED CHANNELS IN<br>SUB GROUP {0}"),
    NO_ASSIGNED_VIEWGROUP: qsTr("NO ASSIGNED CHANNELS IN<br>VIEW GROUP {0}"),
    NO_ASSIGNED_MG: qsTr("NO ASSIGNED CHANNELS IN<br>MUTE GROUP {0}"),
    SAVE_TO_SHOW: qsTr("SAVE TO SHOW"),
    DASHBOARD: qsTr("DASHBOARD"),
    INCOMPATIBLE_CHANNEL_TYPE: qsTr("INCOMPATIBLE CHANNEL TYPE"),
    MIXER_RESET: qsTr("MIXER RESET"),
    SAVE_SHOW_WITH_NAME: qsTr("SAVE SHOW WITH NAME:"),
    NEW_SHOW_NAME: qsTr("NEW SHOW NAME:"),
    SHOW_ALREADY_EXISTS: qsTr("SHOW ALREADY EXISTS"),
    DELETE_SHOW: qsTr('DELETE SHOW "{0}"?'),
    SAVE_SNAPSHOT_WITH_NAME: qsTr("SAVE SNAPSHOT WITH NAME:"),
    NEW_SNAPSHOT_NAME: qsTr("NEW SNAPSHOT NAME:"),
    DELETE_SNAPSHOT: qsTr('DELETE SNAPSHOT "{0}"?'),
    LOAD_THE_INITIAL_MIXER_STATE: qsTr("LOAD THE INITIAL MIXER STATE?"),
    ERR_DELETESHOW: qsTr("ERROR DELETING SHOW."),
    ERR_CREATESHOW: qsTr("ERROR CREATING SHOW."),
    ERR_LOADSHOW: qsTr("ERROR LOADING SHOW."),
    ERR_SAVESHOW: qsTr("ERROR SAVING SHOW PARAMETERS."),
    ERR_RENAMESHOW: qsTr("ERROR RENAMING SHOW."),
    ERR_SAVEINIT: qsTr("CANNOT RESAVE * INIT * SNAPSHOT."),
    ERR_SAVESNAPSHOT: qsTr("ERROR SAVING SNAPSHOT."),
    ERR_LOADSNAPSHOT: qsTr("ERROR LOADING SNAPSHOT."),
    ERR_DELETESNAPSHOT: qsTr("ERROR DELETING SNAPSHOT."),
    ERR_RENAMEINIT: qsTr("CANNOT RENAME * INIT * SNAPSHOT."),
    ERR_RENAMESNAPSHOT: qsTr("ERROR RENAMING SNAPSHOT."),
    ERR_DELETEPRESET: qsTr("ERROR DELETING PRESET."),
    ERR_WRITEPRESET: qsTr("ERROR WRITING PRESET."),
    ERR_RENAMEPRESET: qsTr("ERROR RENAMING PRESET."),
    SNAPLOAD: qsTr("{0}"),
    INITIAL_VALUES_LOADED: qsTr("INITIAL VALUES LOADED."),
    MIX: qsTr("MIX"),
    AUX_SENDS: qsTr("AUX SENDS"),
    AUX_SENDS_X: qsTr("AUX SENDS: {0}"),
    FX_SENDS: qsTr("FX SENDS"),
    FX_EDIT: qsTr("FX EDIT"),
    GROUPS: qsTr("GROUPS"),
    THRESHOLD: qsTr("THRESHOLD"),
    REVERB_SEND: qsTr("REVERB SEND"),
    CHORUS_SEND: qsTr("CHORUS SEND"),
    DELAY_SEND: qsTr("DELAY SEND"),
    ROOM_SEND: qsTr("ROOM SEND"),
    HPF_FREQ: qsTr("HPF FREQ"),
    NOTCH_FREQ: qsTr("NOTCH FREQ"),
    METERS: qsTr("METERS"),
    OUT: qsTr("OUT"),
    IN: qsTr("IN"),
    ME: qsTr("ME"),
    BAND: qsTr("BAND"),
    SETTINGS: qsTr("SETTINGS"),
    MORE_ME: qsTr("MORE ME"),
    DEMO_VERSION: qsTr("DEMO VERSION"),
    LINE_IN: qsTr("LINE IN"),
    LINE: qsTr("LINE"),
    MODE: qsTr("MODE"),
    CHANNEL: qsTr("CHANNEL"),
    SUPPORT: qsTr("SUPPORT"),
    RENAME_CHANNEL: qsTr("RENAME CHANNEL ({0})"),
    CENTER: qsTr("CENTER"),
    SETUP: qsTr("SETUP"),
    JUMP_TO: qsTr("JUMP TO"),
    FUNCTIONS: qsTr("FUNCTIONS"),
    BACK: qsTr("BACK"),
    SAVE_PRESET_WITH_NAME: qsTr("SAVE PRESET WITH NAME:"),
    RENAME_PRESET: qsTr("RENAME PRESET:"),
    NO_ACTIVE_SHOW: qsTr("NO ACTIVE SHOW"),
    RTA: qsTr("RTA"),
    DEESSER: qsTr("DE-ESSER"),
    INPUTS: qsTr("INPUTS"),
    ARE_YOU_SURE: qsTr("ARE YOU SURE?"),
    HI_Z: qsTr("HI-Z"),
    ABOUT: qsTr("ABOUT"),
    LIVE: qsTr("LIVE"),
    FIXED: qsTr("FIXED"),
    MUTE_GROUP_X: qsTr("MUTE GROUP {0}"),
    TAP_X_BPM: qsTr("TAP {0} BPM"),
    MOUNTCHANGED: qsTr("MOUNT CHANGED"),
    MOUNT: qsTr("USB INSERTED"),
    UNMOUNT: qsTr("USB REMOVED"),
    DISABLED: qsTr("DISABLED"),
    ENABLED: qsTr("ENABLED"),
    SINGLE: qsTr("SINGLE"),
    MULTIPLE: qsTr("MULTIPLE"),
    LOCAL: qsTr("LOCAL"),
    GLOBAL: qsTr("GLOBAL"),
    LEVEL: qsTr("LEVEL"),
    TREBLE: qsTr("TREBLE"),
    MID: qsTr("MID"),
    BASS: qsTr("BASS"),
    DB: qsTr("dB"),
    MS: qsTr("ms"),
    HZ: qsTr("hz"),
    NO_CONTROLS_FOR_THIS_CHANNEL: qsTr("NO CONTROLS FOR THIS CHANNEL"),
    UNASSIGN_ME: qsTr("UNASSIGN ME"),
    ASSIGN_ME: qsTr("ASSIGN ME"),
    UNASSIGN_MY_OUT: qsTr("UNASSIGN 'MY OUT'"),
    ASSIGN_MY_OUT: qsTr("ASSIGN 'MY OUT'"),
    NO_SEND_LEVELS: qsTr("NO SEND LEVELS"),
    OK: qsTr("OK"),
    CANCEL: qsTr("CANCEL"),
    FULL: qsTr("FULL"),
    RELOAD_UI: qsTr("RELOAD UI FOR CHANGES TO TAKE EFFECT?"),
    BAD_BROWSER: qsTr("THIS BROWSER DOESN'T SUPPORT WEBSOCKETS. PLEASE USE A DIFFERENT BROWSER."),
    AFS_FIXED_INFO: qsTr("Feedback measurement mode. Please ensure that<br>no other sounds are coming into the inputs except<br>the microphone-speaker feedback tone."),
    RECORDINGS: qsTr("Recordings"),
    READING: qsTr("Reading..."),
    FIRMWARE_FOUND: qsTr("A firmware update image was found on the plugged USB device.<br><br>Perform a mixer update?"),
    FIRMWARE_UPDATED: qsTr("Update succeeded.<br>Please turn the unit off for 10 seconds, power back on and reload this page.<br>Note, your device's wireless might need manual reconnection."),
    MSGBTN_UPDATE: qsTr("Update"),
    MSGBTN_CANCEL: qsTr("Cancel"),
    MSGBTN_OK: qsTr("Ok"),
    UPDATE_ALREADY: qsTr("The update has been attempted once already.<br><br>Please reboot the device to resume / try again."),
    UPDATE_COMPLETED: qsTr("System updated. Please power cycle the device and reload this page for the update to take effect."),
    UPDATE_ERROR: qsTr("Error performing update. "),
    REC_ERRSEQ: qsTr("Recorder: Error writing sequential file to the USB stick (out of space?)."),
    REC_ERRWRITE: qsTr("Recorder: Error writing USB stick (out of space?)."),
    REC_ERRNOSTICK: qsTr("Recorder: USB stick is not inserted to the RECORD slot."),
    REC_ERRNOACCESS: qsTr("Recorder: Unable to access USB stick for writing."),
    REC_ERRCREATE: qsTr("Recorder: Unable to create a file on the USB stick."),
    SHOWEXP_NOTFOUND: qsTr("Export/Import: Item not found"),
    SHOWEXP_USBNOTFOUND: qsTr("USB stick not found"),
    SHOWEXP_WRITEERR: qsTr("Export failed: Unable to access stick for writing"),
    SHOWEXP_INTREADERR: qsTr("Export failed: Error reading the source folder."),
    SHOWEXP_EXPFAILED: qsTr("Some files failed to export."),
    SHOWEXP_SUCCESS: qsTr("EXPORT SUCCESSFUL"),
    SHOWIMP_FAILED: qsTr("Some files failed to import."),
    SHOWIMP_SUCCESS: qsTr("IMPORT SUCCESSFUL"),
    SHOWIMP_NOTFOUND: qsTr("IMPORT ERROR: SOURCE NOT FOUND"),
    SHOWIMP_FILNOTFOUND: qsTr("NO RELEVANT FILES FOUND ON THE USB"),
    IMPORT_SHOW_FROM_USB: qsTr("IMPORT SHOW FROM USB"),
    NO_SHOW_SELECTED: qsTr("NO SHOW SELECTED"),
    EXPORT_SHOW_TO_USB: qsTr("EXPORT SHOW TO USB: {0}"),
    IMPORT_SHOW: qsTr("IMPORT SHOW"),
    EXPORT_SHOW: qsTr("EXPORT SHOW"),
    LANGUAGE: qsTr("LANGUAGE"),
    NO_ME_CHANNELS: qsTr("NO 'ME' CHANNELS"),
    NO_AUX_OUT: qsTr("NO AUX OUT"),
    PADS: qsTr("PADS"),
    CUE: qsTr("CUE"),
    AUTO: qsTr("AUTO"),
    FRAME_RATE: qsTr("FRAME RATE"),
    DISABLE_RETINA: qsTr("DISABLE RETINA"),
    DISABLE_RESCALING: qsTr("DISABLE RESCALING"),
    GUI_PERFORMANCE: qsTr("GUI PERFORMANCE"),
    HEADPHONES_OUT: qsTr("HEADPHONES OUT"),
    BUTTON_FUNCTION: qsTr("BUTTON FUNCTION"),
    KINETIC_SCROLL: qsTr("KINETIC SCROLL"),
    FADER_GLOW: qsTr("FADER GLOW"),
    DISABLE_LED_METERS: qsTr("DISABLE LED METERS"),
    MASTER_LOCK: qsTr("MASTER LOCK"),
    HIDE_COMP_GATE: qsTr("HIDE COMP/GATE"),
    HIDE_DB_MARKS: qsTr("HIDE DB MARKS"),
    PIN_SO_FOR_AUX_FX_SENDS: qsTr("PIN SO FOR AUX/FX SENDS"),
    PIN_SLIDEOUT_IN_MIX_MODE: qsTr("PIN SLIDEOUT IN MIX MODE"),
    SOLO_MODE: qsTr("SOLO MODE"),
    SOLO_ROUTING: qsTr("SOLO ROUTING"),
    HEADPHONES: qsTr("HEADPHONES"),
    HP: qsTr("HP"),
    AUTOCLOSE_SLIDEOUT: qsTr("AUTOCLOSE SLIDEOUT"),
    METER_QUANTISATION: qsTr("METER QUANTISATION"),
    RECORD_MODE: qsTr("RECORD MODE"),
    MIXER_SCROLLING: qsTr("MIXER SCROLLING"),
    DIM_LED_METERS: qsTr("DIM LED METERS"),
    UTILITY: qsTr("UTILITY"),
    BIT_32: qsTr("32 bit"),
    BIT_24: qsTr("24 bit"),
    BIT_16: qsTr("16 bit"),
    FINGER: qsTr("FINGER"),
    FINGERS: qsTr("FINGERS"),
    IMPORT_ALL_PRESETS: qsTr("IMPORT ALL PRESETS"),
    EXPORT_ALL_PRESETS: qsTr("EXPORT ALL PRESETS"),
    NO_CONNECTION_TO_MIXER: qsTr("NO CONNECTION TO MIXER"),
    OFFLINE: qsTr("OFFLINE"),
    VERSION: qsTr("VERSION"),
    COPY_TO_CLIPBOARD: qsTr("COPY TO CLIPBOARD"),
    COPYRIGHT_MSG: qsTr("All third party marks are the trademarks of their respective owners. These marks are used to identify<br>product sounds that were reviewed in the creation of this product and use of these marks do not im-<br>ply an affiliation, endorsement or association with Harman International Industries, Incorporated."),
    FILTER: qsTr("FILTER"),
    DISPLAY: qsTr("DISPLAY"),
    SENSITIVITY: qsTr("SENSITIVITY"),
    CLEAR_FIXED: qsTr("CLEAR FIXED"),
    CLEAR_ALL: qsTr("CLEAR ALL"),
    CLEAR_LIVE: qsTr("CLEAR LIVE"),
    NAME_SSID: qsTr("NAME SSID"),
    SUBNET_MASK: qsTr("SUBNET MASK"),
    WIRELESS_NETWORK: qsTr("WIRELESS NETWORK"),
    SECURITY_OPTIONS: qsTr("SECURITY OPTIONS"),
    LAN_IP_ADDRESS: qsTr("LAN IP ADDRESS"),
    UP: qsTr("UP"),
    DOWN: qsTr("DOWN"),
    ETHERNET: qsTr("ETHERNET"),
    HOTSPOT: qsTr("HOTSPOT"),
    CLOSE: qsTr("CLOSE"),
    COPY_MIX: qsTr("COPY MIX"),
    NO_CONNECTION: qsTr("NO CONNECTION"),
    NO_CURRENT_SNAPSHOT: qsTr("NO CURRENT SNAPSHOT"),
    PATTERNED_BACKGROUND: qsTr("PATTERNED BACKGROUND"),
    ROUTING: qsTr("ROUTING"),
    INPUT_SOURCE: qsTr("INPUT SOURCE"),
    HARDWARE: qsTr("HARDWARE"),
    USB: qsTr("USB"),
    MULTI_TRACK: qsTr("MULTI-TRACK"),
    OUTPUT_DESTINATION: qsTr("OUTPUT DESTINATION"),
    L: qsTr("L"),
    R: qsTr("R"),
    RECORDING_DROPOUT: qsTr("RECORDING DROPOUT"),
    USB_REC_TOO_SLOW: qsTr("USB REC. TOO SLOW"),
    USB_REC_BUFFER: qsTr("USB REC. BUFFER"),
    RECORDER_IS_BUSY: qsTr("RECORDER IS BUSY..."),
    IMPORT_USER_CONFIG: qsTr("IMPORT USER CONFIG"),
    EXPORT_USER_CONFIG: qsTr("EXPORT USER CONFIG"),
    OVERVIEW: qsTr("OVERVIEW"),
    CHANNEL_SOURCE: qsTr("CHANNEL SOURCE"),
    CHANNEL_OUTPUT_DESTINATION: qsTr("CHANNEL OUTPUT DESTINATION"),
    MISC: qsTr("MISC"),
    DISABLE_VU_INPUT_LEVEL: qsTr("DISABLE VU INPUT LEVEL"),
    DISABLE_VU_PEAK: qsTr("DISABLE VU PEAK"),
    SOLO_TYPE: qsTr("SOLO TYPE"),
    AFL: qsTr("AFL"),
    PFL: qsTr("PFL"),
    WRONG_VALUE: qsTr("WRONG VALUE"),
    INPUT_DELAY: qsTr("INPUT DELAY"),
    OUTPUT_DELAY: qsTr("OUTPUT DELAY"),
    PEDAL_FUNCTION: qsTr("PEDAL FUNCTION"),
    CONFIG_WARNING: qsTr("Warning: only the visual/graphics settings specific to this device will be stored.<br>These settings do not affect the operation of the mixer."),
    SET_TO_ZERO_DB: qsTr("SET TO ZERO DB"),
    SET_OUTPUT_DELAY: qsTr("SET OUTPUT DELAY"),
    SET_OUTPUT_DELAY_LEFT: qsTr("LEFT DELAY"),
    SET_OUTPUT_DELAY_RIGHT: qsTr("RIGHT DELAY"),
    MASTER_PRESETS: qsTr("MASTER PRESETS"),
    LEFT: qsTr("LEFT"),
    RIGHT: qsTr("RIGHT"),
    SHORTCUTS: qsTr("SHORTCUTS"),
    SLAVE: qsTr("SLAVE"),
    SUB: qsTr("SUB"),
    METERS_UNIT: qsTr("meters"),
    SAMPLES: qsTr("samples"),
    SMPL: qsTr("smpl"),
    FT: qsTr("ft"),
    EXCEEDS_MAXIMUM_DELAY: qsTr("EXCEEDS MAXIMUM DELAY"),
    START_STOP_PLAYER: qsTr("START/STOP PLAYER"),
    START_STOP_RECORDING: qsTr("START/STOP RECORDING"),
    NONE: qsTr("NONE"),
    ISOLATION: qsTr("ISOLATION"),
    MIC_GAIN: qsTr("MIC GAIN"),
    PHASE: qsTr("PHASE"),
    CHANNELS: qsTr("CHANNELS"),
    BUSSES: qsTr("BUSSES"),
    MATRICES: qsTr("MATRICES"),
    MATRIX: qsTr("MATRIX"),
    HOLD: qsTr("HOLD"),
    COMP: qsTr("COMP"),
    DEPTH: qsTr("DEPTH"),
    ISOLATE: qsTr("ISOLATE"),
    PATCHING: qsTr("PATCHING"),
    DETUNE: qsTr("DETUNE"),
    DENSITY: qsTr("DENSITY"),
    HPF: qsTr("HPF"),
    PANNING: qsTr("PANNING"),
    COMPRESSOR: qsTr("COMPRESSOR"),
    GEQ: qsTr("GEQ"),
    CASCADE: qsTr("CASCADE"),
    CASCADE_MASTER: qsTr("CASCADE MASTER"),
    SOUNDCHECK: qsTr("SOUNDCHECK"),
    DIRECT_OUT: qsTr("DIRECT OUT"),
    IOSYS: qsTr("IOSYS"),
    LOCATE: qsTr("LOCATE"),
    ENABLE: qsTr("ENABLE"),
    DISABLE: qsTr("DISABLE"),
    NAME: qsTr("NAME"),
    EMPTY: qsTr("EMPTY"),
    SESSIONS: qsTr("SESSIONS"),
    MIXER_PATCH: qsTr("MIXER PATCH"),
    NO_PATCH: qsTr("NO PATCH"),
    SPACE_REMAINING: qsTr("SPACE REMAINING:"),
    SD: qsTr("SD"),
    EDIT_CHANNEL: qsTr("EDIT CHANNEL"),
    ETH: qsTr("ETH"),
    SD_MTK: qsTr("SD MTK"),
    RESET_ALL: qsTr("RESET ALL"),
    NOTCH_F: qsTr("NOTCH F."),
    DIRECT_OUTPUT: qsTr("DIRECT OUTPUT"),
    FADER_POSITION: qsTr("FADER POSITION"),
    MASTER_CHANNEL_RANGE: qsTr("MASTER CHANNEL RANGE"),
    IOSYS_PRESET_LOADING: qsTr("IOSYS PRESET LOADING"),
    MTX: qsTr("MTX"),
    SWITCH_TO_MATRIX: qsTr("SWITCH TO MATRIX"),
    SWITCH_TO_AUX: qsTr("SWITCH TO AUX"),
    GATE_PRESETS: qsTr("GATE PRESETS"),
    AFS_PRESETS: qsTr("AFS 2 PRESETS"),
    PRE_PROCESSING: qsTr("PRE PROCESSING"),
    POST_PROCESSING: qsTr("POST PROCESSING"),
    ADDITIONAL_CHANNEL_DESTINATION: qsTr("DIRECT OUTPUT"),
    NO_PAN_ON_MONO_MATRIX: qsTr("NO PAN<br>ON MONO MATRIX"),
    NO_USB_DEVICE_SELECTED: qsTr("NO USB DEVICE SELECTED"),
    GLOBAL_PRE_FADE_AUX_SEND_POINT: qsTr("GLOBAL AUX SEND POINT"),
    SHUFFLE: qsTr("SHUFFLE"),
    EZ_EQ: qsTr("EZ EQ"),
    MOREME_PORTRAIT_MODE: qsTr("MOREME PORTRAIT MODE"),
    RESET_LOCAL_SETTINGS: qsTr("RESET LOCAL SETTINGS"),
    SYNC_ID: qsTr("SYNC ID"),
    SYNC_SELECTED_CH: qsTr("SYNC SELECTED CHANNEL"),
    ACCESS_LIMITING: qsTr("ACCESS LIMITING"),
    PASSWORD: qsTr("PASSWORD"),
    ACCESS: qsTr("ACCESS"),
    MONITOR_ACCESS_LIMIT: qsTr("ACCESS LIMIT (LOCAL)"),
    ALLOW_ACCESS_FOR: qsTr("ALLOW ACCESS FOR"),
    ALLOW_CLIENT_ACCESS_FOR: qsTr("ALLOW CLIENT ACCESS FOR"),
    LOCAL_AUX_CONTROL: qsTr("LOCAL AUX CONTROL (SOFT ACCESS ENABLER)"),
    MASTER_VOLUME: qsTr("MASTER VOLUME"),
    ACCOUNT: qsTr("ACCOUNT"),
    MASTER_PASSWORD_PROTECTION: qsTr("MASTER PASSWORD PROTECTION (GLOBAL)"),
    LOG_IN: qsTr("LOG IN"),
    LOG_OUT: qsTr("LOG OUT"),
    AUX_LEVELS: qsTr("AUX LEVELS"),
    AUX_PROCESSING: qsTr("AUX PROCESSING"),
    MIX_LEVELS: qsTr("MIX LEVELS"),
    MIX_GAIN: qsTr("MIX GAIN"),
    MIX_PROCESSING: qsTr("MIX PROCESSING"),
    MASTER_LEVEL: qsTr("MASTER LEVEL"),
    MASTER_PROCESSING: qsTr("MASTER PROCESSING"),
    GLOBAL_SETTINGS: qsTr("GLOBAL SETTINGS"),
    SET_MASTER_PASS: qsTr("SET MASTER PASSWORD"),
    ENTER_PASS_TO_UNLOCK: qsTr("ENTER PASSWORD TO UNLOCK"),
    ENTER_PASS: qsTr("ENTER PASSWORD"),
    WRONG_PASSWORD: qsTr("WRONG PASSWORD"),
    UNLOCKED: qsTr("UNLOCKED"),
    LOGGED_IN: qsTr("LOGGED IN"),
    LOGGED_OUT: qsTr("LOGGED OUT"),
    LOCAL_SETTINGS_PRESETS: qsTr("LOCAL SETTINGS PRESETS")
};
langBase.cn = {
    alertWaiting: "此功能暂未开放",
    websocketError: "websocket 连接错误， 请检查网络",
    phantomConfirm: "确定改变 48V 供电?",
    changeChannel: "通道选择",
    websitegate: "网关",
    promptssid: "设置SSID",
    promptpassword: "设置密码",
    lang: "中文",
    APPLY: "应用",
    HOME: "主页",
    FX_REVERB: "混响",
    FX_ECHO: "回声",
    FX_DELAY: "延时",
    ChannelSet: "通道设置",
    SceneShot: "场景快照",
    VUDis: "电平预览",
    FXSend: "FX发送",
    MainSend: "母线发送",
    BASESET: "基础设置",
    MAINALLO: "母线分配",
    USBREC: "USB录音",
    LINK: "联动",
    COLOR: "颜色",
    COVER: "覆盖",
    MAIN_OUT: "主输出",
    me_REVERB: "混响",
    GLOBALSET: "全局设置",
    SCENEHANDLE: "请选择对 ({0}) 的操作?",
    SCENENAME: "名称",
    ASSIGN_SUB_GROUP: "分配到编组 {0}",
    ATTACK: "启动",
    AUX: "辅助",
    AUX_EQ: "辅助EQ",
    AUX_MASTERS: "辅助主推子",
    AUX_MASTER_LEVELS: "辅助主推子电平",
    AUX_SENDS_FOR: "辅助发送: {0}",
    BANKS: "分页",
    BASS_GAIN: "低频增益",
    BYPASS: "旁通",
    CH: "通道",
    CHANNEL_SAFES: "通道安全",
    FX_SENDS_X: "效果发送: {0}",
    CHANNEL_PRESETS: "通道预置",
    CHORUS: "合唱",
    CHORUS_FX_GLOBAL: "合唱效果 (GLOBAL)",
    CLEAR_SOLO: "消除SOLO",
    CONFIG: "配置",
    CONFIGURATION: "配置",
    CONNECTED_DEVICE_NAME: "接入设备名称",
    COPY_SETTINGS: "复制设置",
    CURRENT_SHOW: "当前场景",
    DELAY: "延时",
    DELAY_FX_GLOBAL: "延时效果 (GLOBAL)",
    DELAY_LENGTH: "延时长短",
    DELETE: "删除",
    DISABLE_STEREO_LINK: "关闭立体效果链接",
    DOCUMENTATION: "文件",
    DYN: "动态学",
    EDIT: "编辑",
    EQ: "均衡器",
    EXPORT: "导出",
    FAV_SHOW: "偏爱场景",
    FEEDBACK: "反馈",
    FEEDBACK_AMOUNT: "反馈总量",
    FREQ: " 频率",
    FX: "效果",
    FX_MODE_DEFAULT: "默认效果模式",
    FX_RETURNS: "效果返回",
    FX_RETURNS_TO_AUX: "效果返回到: {0}",
    GAIN: "增益",
    PREGAIN: "预增益",
    GROUP: "编组",
    HELP: "帮助",
    HF_DAMPING: "高频衰减",
    HIGHPASS_FILTER: "高通滤波",
    IMPORT: "导入",
    INPUT: "输入",
    LENGTH_SUBDIVISION: "长度细分",
    LOAD: "载入",
    LOAD_PRESET: "载入预设置",
    LOCK: "锁定",
    LOCKED: "鎖定的",
    LOWPASS_FILTER: "低通滤波",
    MANUAL: "手动",
    MASTER: "主控",
    MASTER_EQ: "总控EQ",
    MEDIA: "多媒体",
    MEDIA_FADER_BEFORE_CH1: "通道1前置多媒体推子",
    MIX_GAIN: "调音增益",
    MUTE: "静音",
    MUTE_ALL: "全部静音",
    MUTE_FX: "FX效果静音",
    MUTE_GROUP_BUTTON_ASSIGN: "分组按钮分配静音",
    MUTE_GROUPS: "分组静音",
    MUTES: "静音",
    NETWORK: "网络",
    NEW: "新建",
    NEW_SNAPSHOT: "新记忆点",
    NEXT_SNAPSHOT: "下一个记忆点",
    NORM: "标准",
    OFF: "关",
    ON: "开",
    ONLINE_SUPPORT: "在线支持",
    PASTE_SETTINGS: "粘贴设置",
    PERMISSIONS: "权限",
    PERMIT: "权限",
    PHANTOM: "幻象供电",
    PLAY: "播放",
    PLAYER: "播放器",
    PLAYLIST: "播放列表",
    PRESETS: "预置",
    RATIO: "比例",
    RECORD: "录音",
    RELEASE: "释放",
    NAME: "名称",
    RENAME: "重命名",
    RESET: "重设",
    RESET_CHANNEL: "重设通道",
    REVERB: "混响器",
    REVERB_TIME: "混响时间",
    REVERB_FX_GLOBAL: "混响效果 (GLOBAL)",
    ROOM: "房间模式",
    SAVE: "保存",
    SAVE_AS: "另存为",
    SEND: "发送",
    SENDS: "发送",
    SG: "编组",
    SHOWS: "场景",
    SNAPSHOTS: "记忆点",
    SOCIAL: "社交",
    SOLO: "独奏",
    SPEED: "速度",
    STEREO_LINK: "立体声关联",
    SUB_GROUP_FADER_ASSIGN: "编组推子分配",
    SUB_GROUP_SPREAD: "编组扩展",
    SUB_GROUPS: "编组",
    SUBS: "编组",
    TAP_TEMPO: "敲击节拍",
    THIN: "柔和效果",
    TOTAL_VIEW: "总视窗",
    UNASSIGN_SUB_GROUP: "解除编组 {0}",
    UPDATE_CURRENT_SNAPSHOT: "更新当前记忆点",
    USB_MEDIA_FILES: "USB多媒体文件",
    VIEW_GROUP_BUTTON_ASSIGN: "显示分组按钮分配",
    VIEW_GROUPS: "分组显示",
    VIEWS: "视窗",
    SHOW_ALL_CHANNELS: "显示所有通道",
    PLACE_AFTER_INPUTS: "置于输入后",
    PLACE_BEFORE_INPUTS: "置于输入前",
    GATE: "门限",
    MUTE_FX_CANCEL: "取消FX静音效果",
    MUTE_ALL_CANCEL: "取消全部静音效果",
    MUTEGROUP_1_ACTIVATED: "激活编组 {0} 静音效果",
    MUTEGROUP_1_DEACTIVATED: "取消编组 {0} 静音效果",
    NO_SNAPSHOT: "无记忆点",
    LOAD_NEXT_SNAPSHOT: "载入下一个记忆点",
    CHANNEL_EQ_PRESETS: "通道EQ预置",
    AUX_EQ_PRESETS: "辅助EQ预置",
    MASTER_EQ_PRESETS: "主控EQ预置",
    CHANNEL_DYN_PRESETS: "通道动态预置",
    AUX_DYN_PRESETS: "辅助动态预置",
    MASTER_DYN_PRESETS: "主控动态预置",
    DELAY_FX_PRESETS: "FX延迟效果预置",
    CHORUS_FX_PRESETS: "FX合唱效果预置",
    REVERB_FX_PRESETS: "FX混响效果预置",
    ROOM_PRESETS: "房间模式预置",
    DIGITECH_PRESETS: "效果器预置",
    FILES: "文件",
    CONNECTING: "正在载入...",
    KEEP_TAPPING: "保持点击...",
    PLAYLISTS: "播放列表",
    PRESET_LOADED: "预置<br>{0}<br>载入",
    NO_PAN_ON_MONO_AUX: "单声道辅<br>助无声像",
    PARAM_GLOBAL: "{0} 参数(GLOBAL)",
    CLEAR_ALL_SOLOS: "清除所有SOLO",
    POST: "后置",
    PRE: "前置",
    SET_ALL_CHANNELS_TO: '设置所有通道到 "{0}" ?',
    SAVED: "保存",
    REPLACE_PRESET: '替换预置 "{0}" ?',
    REPLACE_SNAPSHOT: '替换记忆点 "{0}" ?',
    FACTORY: "工厂设定",
    USER: "用户",
    DELETE_PRESET: '删除前置 "{0}" ?',
    BPM: "拍速",
    OUT_OF_RANGE: "超出范围",
    ERROR: "报错",
    NO_ASSIGNED_SUBGROUP: '在编组"{0}"不分配通道',
    NO_ASSIGNED_VIEWGROUP: '在显示编组"{0}"上不分配通道',
    NO_ASSIGNED_MG: '在静音编组"{0}"中不分配通道',
    SAVE_TO_SHOW: "保存到场景",
    DASHBOARD: "报表",
    INCOMPATIBLE_CHANNEL_TYPE: "通道类型不匹配",
    MIXER_RESET: "调音台重置",
    SAVE_SHOW_WITH_NAME: "保存场景名称:",
    NEW_SHOW_NAME: "新场景名称:",
    SHOW_ALREADY_EXISTS: "显示已有",
    DELETE_SHOW: '删除场景 "{0}"?',
    SAVE_SNAPSHOT_WITH_NAME: "保存记忆点名称:",
    NEW_SNAPSHOT_NAME: "新记忆点名称:",
    DELETE_SNAPSHOT: '删除记忆点 "{0}"?',
    LOAD_THE_INITIAL_MIXER_STATE: "载入原始的调音台状态",
    ERR_DELETESHOW: "删除错误场景",
    ERR_CREATESHOW: "创建错误场景",
    ERR_LOADSHOW: "载入错误场景",
    ERR_SAVESHOW: "保存错误场景参数",
    ERR_RENAMESHOW: "重命名错误场景",
    ERR_SAVEINIT: "“初始”记忆点不能保存",
    ERR_SAVESNAPSHOT: "保存记忆点错误",
    ERR_LOADSNAPSHOT: "载入记忆点错误",
    ERR_DELETESNAPSHOT: "删除记忆点错误",
    ERR_RENAMEINIT: "不能重命名“初始”记忆点",
    ERR_RENAMESNAPSHOT: "重命名记忆点错误",
    ERR_DELETEPRESET: "删除前置错误",
    ERR_WRITEPRESET: "写入前置错误",
    ERR_RENAMEPRESET: "重命名前置错误",
    INITIAL_VALUES_LOADED: "导入初始数值",
    MIX: "调音",
    AUX_SENDS: "辅助发送",
    AUX_SENDS_X: "辅助发送: {0}",
    FX_SENDS: "FX效果发送",
    FX_EDIT: "FX效果编辑",
    GROUPS: "编组",
    THRESHOLD: "阀值",
    REVERB_SEND: "发送混响",
    CHORUS_SEND: "合唱效果发送",
    DELAY_SEND: "延时发送",
    ROOM_SEND: "房间模式发送",
    HPF_FREQ: "高频",
    NOTCH_FREQ: "锯齿频率",
    METERS: "仪表",
    OUT: "输出",
    IN: "输入",
    ME: "ME ",
    BAND: "波段",
    SETTINGS: "设置",
    MORE_ME: "关于ME",
    DEMO_VERSION: "DEMO版本",
    LINE_IN: "line输入",
    MODE: "模式",
    CHANNEL: "通道",
    SUPPORT: "支持",
    RENAME_CHANNEL: "重命名通道({0})",
    CENTER: "中心",
    SETUP: "设置",
    JUMP_TO: "跳跃到",
    FUNCTIONS: "功能",
    BACK: "返回",
    SAVE_PRESET_WITH_NAME: "保存前置命名",
    RENAME_PRESET: "前置重命名",
    NO_ACTIVE_SHOW: "无效场景",
    RTA: "RTA比例",
    DEESSER: "DE-ESSER模式",
    INPUTS: "输入",
    ARE_YOU_SURE: "确定？",
    ABOUT: "关于",
    LIVE: "实况",
    FIXED: "解决",
    MUTE_GROUP_X: "分组静音 {0}",
    TAP_X_BPM: "敲击节拍",
    MOUNTCHANGED: "更改总数",
    MOUNT: "插入USB",
    UNMOUNT: "拔掉USB",
    DISABLED: "禁用",
    ENABLED: "激活",
    SINGLE: "单一的",
    MULTIPLE: "多样的",
    LOCAL: "局部",
    GLOBAL: "总体",
    LEVEL: "电平",
    TREBLE: "三重的",
    MID: "中音",
    BASS: "低音",
    DB: "分贝",
    NO_CONTROLS_FOR_THIS_CHANNEL: "本通道不受控",
    UNASSIGN_ME: "没有定义ME",
    ASSIGN_ME: "定义ME",
    UNASSIGN_MY_OUT: "没有标示'MY OUT'",
    ASSIGN_MY_OUT: "标示‘MY OUT’",
    NO_SEND_LEVELS: "电平不发送",
    CANCEL: "取消",
    FULL: "全部",
    RELOAD_UI: "重载变更UI参数是否生效",
    AFS_FIXED_INFO: "测试模式反馈，确保<br>没有任何其他声音输入，麦克风-音箱反馈除外",
    RECORDINGS: "记录",
    READING: "正在读取",
    FIRMWARE_FOUND: "USB设备发现firmware更新现象，确定<br><br>执行更新？",
    MSGBTN_UPDATE: "更新",
    MSGBTN_CANCEL: "取消",
    MSGBTN_OK: "OK",
    UPDATE_ALREADY: "更新完毕.<br><br>重启设备/再重启",
    UPDATE_COMPLETED: "系统更新完毕.重启系统并重载这个界面.",
    UPDATE_ERROR: "更新错误报告",
    REC_ERRSEQ: "报告：相关文件无法写入USB(内存不足？)",
    REC_ERRWRITE: "报告：无法写入USB(内存不足？)",
    REC_ERRNOSTICK: "报告：USB没有插入",
    REC_ERRNOACCESS: "报告：无法读写USB",
    REC_ERRCREATE: "报告：USB无法创建文件",
    SHOWEXP_NOTFOUND: "输入/输出:无相关文件",
    SHOWEXP_USBNOTFOUND: "USB不能识别",
    SHOWEXP_WRITEERR: "输出失效：失效标签，无法写入信息",
    SHOWEXP_INTREADERR: "输出失效:源文件无法读写",
    SHOWEXP_EXPFAILED: "部分文件无法导出",
    SHOWEXP_SUCCESS: "导出成功",
    SHOWIMP_FAILED: "部分文件无法载入",
    SHOWIMP_SUCCESS: "导入成功",
    SHOWIMP_NOTFOUND: "导入错误信息:找不到原文件",
    SHOWIMP_FILNOTFOUND: "USB没有相关的文件",
    IMPORT_SHOW_FROM_USB: "从USB导入SHOW",
    NO_SHOW_SELECTED: "没有选择SHOW",
    EXPORT_SHOW_TO_USB: "导出SHOW到USB: {0}",
    IMPORT_SHOW: "导入SHOW",
    EXPORT_SHOW: "导出SHOW",
    LANGUAGE: "语言",
    CUE: "暗示",
    AUTO: "自动",
    ACCESS_LIMITING: "访问权限",
    PASSWORD: "密码",
    ACCESS: "访问",
    ALLOW_ACCESS_FOR: "允许访问",
    GLOBAL_SETTINGS: "全部设置",
    MASTER_PROCESSING: "主控处理中",
    MASTER_VOLUME: "主控数值",
    ACCOUNT: "总值",
    FRAME_RATE: "帧数等级",
    DISABLE_RETINA: "RETINA禁用",
    DISABLE_RESCALING: "缩放禁用",
    GUI_PERFORMANCE: "执行GUI",
    HEADPHONES_OUT: "耳机输出",
    BUTTON_FUNCTION: "按钮功能",
    KINETIC_SCROLL: "触点滚动",
    FADER_GLOW: "推子GLOW",
    DISABLE_LED_METERS: "关闭LED",
    MASTER_LOCK: "总线鎖",
    HIDE_COMP_GATE: "隐藏压缩/阀值",
    HIDE_DB_MARKS: "隐藏DB标示",
    PIN_SO_FOR_AUX_FX_SENDS: "拼SO到AUX/FX发送",
    PIN_SLIDEOUT_IN_MIX_MODE: "调音界面下拉窗总展开",
    SOLO_MODE: "SOLO模式",
    SOLO_ROUTING: "SOLO路径",
    HEADPHONES: "耳机",
    HP: "耳机",
    AUTOCLOSE_SLIDEOUT: "自动关闭SLIDEOUT",
    METER_QUANTISATION: "仪表数量",
    RECORD_MODE: "记录模式",
    MIXER_SCROLLING: "调音台滚动模式",
    DIM_LED_METERS: "DIM LED仪表",
    UTILITY: "功能",
    FINGER: "手指",
    FINGERS: "手指",
    IMPORT_ALL_PRESETS: "导入所以前置",
    EXPORT_ALL_PRESETS: "导出所有前置",
    NO_CONNECTION_TO_MIXER: "没有连接到调音台",
    OFFLINE: "离线",
    VERSION: "版本",
    COPY_TO_CLIPBOARD: "COPY到剪切板",
    COPYRIGHT_MSG: "所有的第三方标示均为他们固有的商标，用于定义<br>产品，评估此产品以及此标示，备注Harman公司，受法律保护.",
    FILTER: "滤波器",
    DISPLAY: "显示",
    SENSITIVITY: "敏感度",
    CLEAR_FIXED: "消除FIXED",
    CLEAR_ALL: "消除所有",
    CLEAR_LIVE: "消除LIVE",
    NAME_SSID: "名称（SSID）",
    SUBNET_MASK: "子網掩碼",
    WIRELESS_NETWORK: "无线网络",
    SECURITY_OPTIONS: "安全设置",
    LAN_IP_ADDRESS: "局域網IP地址",
    UP: "向上",
    DOWN: "向下",
    ETHERNET: "以太网",
    HOTSPOT: "热点",
    NO_CONNECTION: "没有连接到调音台",
    TRANSLATIONS_END: "-----"
};